# Generated by Django 4.0.4 on 2022-04-23 08:50

import applications.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', applications.account.models.UserManager()),
            ],
        ),
    ]
